/**
 * AI Block Content Generator
 * 
 * Takes a business type + info and generates content specifically for the
 * Allbirds-style AI template blocks. The LAYOUT stays the same (the blocks),
 * but the CONTENT (text, images, categories, CTAs) is generated by AI
 * based on what the user's business actually is.
 */

import { AI_TEMPLATE_PRESET } from "@/lib/templates/presets/ai-preset";
import type { TemplateBlock } from "@/components/storefront/TemplateBlockRenderer";

// ─── Industry Image Maps ────────────────────────────────────
// High-quality Unsplash images grouped by industry so we always show relevant visuals

const INDUSTRY_IMAGES: Record<string, {
  hero: string;
  categories: string[];
  promos: string[];
  products: string[];
}> = {
  "real-estate": {
    hero: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1920&h=1080&fit=crop",
    categories: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800&h=1040&fit=crop",
    ],
    promos: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=700&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=700&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=700&h=1000&fit=crop",
    ],
    products: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=600&h=600&fit=crop",
    ],
  },
  "restaurant": {
    hero: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1920&h=1080&fit=crop",
    categories: [
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&h=1040&fit=crop",
    ],
    promos: [
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=700&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=700&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=700&h=1000&fit=crop",
    ],
    products: [
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1499028344343-cd173ffc68a9?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1432139509613-5c4255a1d96f?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=600&h=600&fit=crop",
    ],
  },
  "technology": {
    hero: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1920&h=1080&fit=crop",
    categories: [
      "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=800&h=1040&fit=crop",
    ],
    promos: [
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=700&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=700&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=700&h=1000&fit=crop",
    ],
    products: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1526738549149-8e07eca6c147?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&h=600&fit=crop",
    ],
  },
  "fitness": {
    hero: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1920&h=1080&fit=crop",
    categories: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&h=1040&fit=crop",
    ],
    promos: [
      "https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=700&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=700&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1576678927484-cc907957088c?w=700&h=1000&fit=crop",
    ],
    products: [
      "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1518459031867-a89b944bffe4?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1593079831268-3381b0db4a77?w=600&h=600&fit=crop",
    ],
  },
  "beauty": {
    hero: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1920&h=1080&fit=crop",
    categories: [
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1487412912498-0447578fcca8?w=800&h=1040&fit=crop",
    ],
    promos: [
      "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=700&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=700&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=700&h=1000&fit=crop",
    ],
    products: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1571875257727-256c39da42af?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=600&h=600&fit=crop",
    ],
  },
  "fashion": {
    hero: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1920&h=1080&fit=crop",
    categories: [
      "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1556906781-9a412961c28c?w=800&h=1040&fit=crop",
    ],
    promos: [
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=700&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1445205170230-053b83016050?w=700&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=700&h=1000&fit=crop",
    ],
    products: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=600&h=600&fit=crop",
    ],
  },
  // Fallback for any industry not explicitly mapped
  "default": {
    hero: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1920&h=1080&fit=crop",
    categories: [
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1497215842964-222b430dc094?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=1040&fit=crop",
      "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=1040&fit=crop",
    ],
    promos: [
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=700&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=700&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=700&h=1000&fit=crop",
    ],
    products: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=600&h=600&fit=crop",
    ],
  },
};

// ─── Resolve industry to image key ──────────────────────────

function resolveIndustryKey(businessType: string): string {
  const bt = businessType.toLowerCase().replace(/[^a-z0-9 ]/g, "");
  
  // Direct matches
  if (bt.includes("real estate") || bt.includes("property") || bt.includes("housing") || bt.includes("apartment") || bt.includes("rental")) return "real-estate";
  if (bt.includes("restaurant") || bt.includes("food") || bt.includes("cafe") || bt.includes("bakery") || bt.includes("catering") || bt.includes("kitchen") || bt.includes("cook")) return "restaurant";
  if (bt.includes("tech") || bt.includes("software") || bt.includes("saas") || bt.includes("app") || bt.includes("digital") || bt.includes("computer") || bt.includes("electronic")) return "technology";
  if (bt.includes("fitness") || bt.includes("gym") || bt.includes("sport") || bt.includes("yoga") || bt.includes("wellness") || bt.includes("health")) return "fitness";
  if (bt.includes("beauty") || bt.includes("cosmetic") || bt.includes("skincare") || bt.includes("makeup") || bt.includes("salon") || bt.includes("spa")) return "beauty";
  if (bt.includes("fashion") || bt.includes("cloth") || bt.includes("shoe") || bt.includes("apparel") || bt.includes("wear") || bt.includes("boutique")) return "fashion";
  
  return "default";
}

function getIndustryImages(businessType: string) {
  const key = resolveIndustryKey(businessType);
  return INDUSTRY_IMAGES[key] || INDUSTRY_IMAGES["default"];
}

// ─── AI Content Generation Prompt ───────────────────────────

export function buildBlockContentPrompt(storeName: string, businessType: string, description?: string): string {
  return `You are a professional website content writer. Generate content for a "${businessType}" business called "${storeName}".
${description ? `Business description: ${description}` : ""}

Generate content that fits into an Allbirds-style modern website layout. Return ONLY valid JSON:

{
  "announcement": ["4 short marquee messages relevant to this ${businessType} business (e.g., promotions, USPs, seasonal offers)"],
  "heroButtons": [
    {"text": "primary CTA text (2-3 words)", "link": "/shop"},
    {"text": "secondary CTA text (2-3 words)", "link": "/about"}
  ],
  "categories": [
    {"title": "category 1 name", "buttonLabels": ["Browse", "View All"]},
    {"title": "category 2 name", "buttonLabels": ["Explore"]},
    {"title": "category 3 name", "buttonLabels": ["Shop Now"]},
    {"title": "category 4 name", "buttonLabels": ["Discover", "See More"]}
  ],
  "featuredProducts": [
    {"title": "product/listing/item name", "description": "short detail", "price": "$XXX", "compareAtPrice": "$XXX"},
    {"title": "product 2", "description": "detail", "price": "$XXX", "compareAtPrice": "$XXX"},
    {"title": "product 3", "description": "detail", "price": "$XXX", "compareAtPrice": "$XXX"},
    {"title": "product 4", "description": "detail", "price": "$XXX", "compareAtPrice": "$XXX"},
    {"title": "product 5", "description": "detail", "price": "$XXX", "compareAtPrice": "$XXX"}
  ],
  "promoTiles": [
    {"title": "promo section 1 name"},
    {"title": "promo section 2 name"},
    {"title": "promo section 3 name"}
  ],
  "productCards": [
    {"name": "item name", "colorway": "variant/detail", "price": "$XX", "compareAtPrice": "$XX", "badge": "NEW or XX% OFF or null"},
    {"name": "item 2", "colorway": "variant", "price": "$XX", "badge": null},
    {"name": "item 3", "colorway": "variant", "price": "$XX", "compareAtPrice": "$XX", "badge": "POPULAR"},
    {"name": "item 4", "colorway": "variant", "price": "$XX", "badge": null},
    {"name": "item 5", "colorway": "variant", "price": "$XX", "compareAtPrice": "$XX", "badge": "NEW"},
    {"name": "item 6", "colorway": "variant", "price": "$XX", "badge": null},
    {"name": "item 7", "colorway": "variant", "price": "$XX", "badge": "HOT"},
    {"name": "item 8", "colorway": "variant", "price": "$XX", "compareAtPrice": "$XX", "badge": null}
  ],
  "tabLabel": "tab label for the product carousel (e.g., Featured, Popular, On Sale)",
  "featuredTabLabel": "tab label for featured carousel (e.g., Bestsellers, Top Picks)",
  "valueProps": [
    {"title": "value prop 1 heading", "description": "1-2 sentence explanation"},
    {"title": "value prop 2 heading", "description": "1-2 sentence explanation"},
    {"title": "value prop 3 heading", "description": "1-2 sentence explanation"}
  ],
  "footerColumns": [
    {"title": "column 1 title", "links": [{"text": "link text", "link": "/path"}]},
    {"title": "column 2 title", "links": [{"text": "link text", "link": "/path"}]},
    {"title": "column 3 title", "links": [{"text": "link text", "link": "/path"}]}
  ]
}

Rules:
- ALL content must be specific to a ${businessType} business — no generic filler
- Product names should be real items/services this business would sell
- Prices should be realistic for this industry
- Categories should be actual ${businessType} categories
- Value props should be genuine USPs for this industry
- For real estate: use property types, neighborhoods, price ranges
- For restaurants: use dishes, cuisines, dining experiences
- For tech: use products, services, solutions
- Keep it professional but warm
- Return ONLY JSON, no markdown fences`;
}

// ─── Build Smart Blocks ─────────────────────────────────────

export interface SmartBlockInput {
  storeName: string;
  storeSlug: string;
  businessType: string;
  description?: string;
  aiContent?: Record<string, unknown>; // AI-generated content
}

export function buildSmartAiBlocks(input: SmartBlockInput): TemplateBlock[] {
  const { storeName, storeSlug, businessType, aiContent } = input;
  const images = getIndustryImages(businessType);
  const blocks = JSON.parse(JSON.stringify(AI_TEMPLATE_PRESET)) as TemplateBlock[];
  const ai = aiContent || {};

  for (const block of blocks) {
    const props = (block.props ||= {});
    switch (block.type) {
      case "aiAnnouncementBar": {
        const msgs = ai.announcement as string[] | undefined;
        props.messages = msgs && msgs.length > 0
          ? msgs
          : [
              `Welcome to ${storeName}`,
              `Trusted ${businessType} services`,
              "Quality you can count on",
              "Contact us today",
            ];
        break;
      }

      case "aiHeroVideo": {
        props.backgroundImage = images.hero;
        props.backgroundVideo = "";
        const heroButtons = ai.heroButtons as Array<{ text: string; link: string }> | undefined;
        props.buttons = heroButtons
          ? heroButtons.map((b) => ({ text: b.text, link: `/store/${storeSlug}${b.link}`, style: "primary" }))
          : [
              { text: "Browse", link: `/store/${storeSlug}/shop`, style: "primary" },
              { text: "About Us", link: `/store/${storeSlug}/about`, style: "primary" },
            ];
        break;
      }

      case "aiCategoryRow": {
        const cats = ai.categories as Array<{ title: string; buttonLabels: string[] }> | undefined;
        const cards = (cats || [
          { title: "Featured", buttonLabels: ["View All"] },
          { title: "Popular", buttonLabels: ["Browse"] },
          { title: "New", buttonLabels: ["Explore"] },
          { title: "Trending", buttonLabels: ["See More"] },
        ]).slice(0, 4);

        props.cards = cards.map((c, i) => ({
          title: c.title,
          image: images.categories[i % images.categories.length],
          overlayOpacity: 15,
          buttons: (c.buttonLabels || ["Browse"]).map((label) => ({
            text: label,
            link: `/store/${storeSlug}/shop`,
          })),
        }));
        break;
      }

      case "aiLargeProductCarousel": {
        const featured = ai.featuredProducts as Array<{
          title: string; description: string; price: string; compareAtPrice?: string;
        }> | undefined;
        const tabLabel = (ai.featuredTabLabel as string) || "Featured";

        const products = (featured || [
          { title: "Featured Item 1", description: "Premium quality", price: "$99", compareAtPrice: "$150" },
          { title: "Featured Item 2", description: "Best seller", price: "$79", compareAtPrice: "$120" },
          { title: "Featured Item 3", description: "New arrival", price: "$59", compareAtPrice: "$90" },
          { title: "Featured Item 4", description: "Limited edition", price: "$129", compareAtPrice: "$200" },
          { title: "Featured Item 5", description: "Customer favorite", price: "$69", compareAtPrice: "$100" },
        ]).slice(0, 5);

        props.tabs = [{
          label: tabLabel,
          products: products.map((p, i) => ({
            title: p.title,
            description: p.description,
            price: p.price,
            compareAtPrice: p.compareAtPrice || undefined,
            image: images.products[i % images.products.length],
            link: `/store/${storeSlug}/shop`,
            isUnisex: true,
          })),
        }];
        break;
      }

      case "aiPromoTiles": {
        const promos = ai.promoTiles as Array<{ title: string }> | undefined;
        const promoTitles = promos || [
          { title: "New Arrivals" },
          { title: "Most Popular" },
          { title: "Special Offers" },
        ];

        props.tiles = promoTitles.slice(0, 3).map((p, i) => ({
          title: p.title,
          image: images.promos[i % images.promos.length],
          buttons: [
            { text: "Explore", link: `/store/${storeSlug}/shop` },
            { text: "Learn More", link: `/store/${storeSlug}/about` },
          ],
        }));
        break;
      }

      case "aiProductCarousel": {
        const cards = ai.productCards as Array<{
          name: string; colorway: string; price: string; compareAtPrice?: string; badge?: string | null;
        }> | undefined;
        const tabLabel = (ai.tabLabel as string) || "Popular";

        const productCards = (cards || [
          { name: "Item 1", colorway: "Standard", price: "$45", compareAtPrice: "$90", badge: "50% OFF" },
          { name: "Item 2", colorway: "Premium", price: "$55", compareAtPrice: "$110", badge: null },
          { name: "Item 3", colorway: "Classic", price: "$37", compareAtPrice: "$75", badge: "NEW" },
          { name: "Item 4", colorway: "Deluxe", price: "$65", badge: null },
          { name: "Item 5", colorway: "Standard", price: "$55", compareAtPrice: "$110", badge: null },
          { name: "Item 6", colorway: "Premium", price: "$70", compareAtPrice: "$140", badge: null },
          { name: "Item 7", colorway: "Limited", price: "$55", badge: "NEW" },
          { name: "Item 8", colorway: "Classic", price: "$62", compareAtPrice: "$125", badge: "POPULAR" },
        ]).slice(0, 8);

        props.tabs = [{
          label: tabLabel,
          products: productCards.map((p, i) => ({
            name: p.name,
            colorway: p.colorway,
            price: p.price,
            compareAtPrice: p.compareAtPrice || undefined,
            image: images.products[i % images.products.length],
            link: `/store/${storeSlug}/shop`,
            badge: p.badge || undefined,
            swatches: [{ color: "#555", label: p.colorway }],
          })),
        }];
        break;
      }

      case "aiValueProps": {
        const vps = ai.valueProps as Array<{ title: string; description: string }> | undefined;
        props.props = vps || [
          { title: "Quality First", description: `We deliver the best in ${businessType}. Every product and service meets our high standards.` },
          { title: "Trusted by Thousands", description: "Join our growing community of satisfied customers who keep coming back." },
          { title: "Expert Support", description: "Our team is here to help you every step of the way. Reach out anytime." },
        ];
        break;
      }

      case "aiFooter": {
        props.copyrightText = `© ${new Date().getFullYear()} ${storeName}. All rights reserved.`;
        const footerCols = ai.footerColumns as Array<{
          title: string; links: Array<{ text: string; link: string }>;
        }> | undefined;

        if (footerCols) {
          props.columns = footerCols.map((col) => ({
            title: col.title,
            links: col.links.map((l) => ({
              text: l.text,
              link: typeof l.link === "string" && l.link.startsWith("/store") ? l.link : `/store/${storeSlug}${String(l.link || "")}`,
            })),
          }));
        } else {
          props.columns = [
            { title: "Help", links: [
              { text: "Contact Us", link: `/store/${storeSlug}/contact` },
              { text: "FAQ", link: `/store/${storeSlug}/faq` },
            ]},
            { title: "Browse", links: [
              { text: "All Products", link: `/store/${storeSlug}/shop` },
              { text: "About Us", link: `/store/${storeSlug}/about` },
            ]},
            { title: "Legal", links: [
              { text: "Policies", link: `/store/${storeSlug}/policies` },
            ]},
          ];
        }
        break;
      }
    }
  }

  return blocks;
}
