import "dotenv/config";
import { prisma } from "./src/lib/db";
import { mergeBespokeTemplateBlocks } from "./src/lib/templates/bespoke-page-content";
import { buildDefaultPageContent } from "./src/lib/templates/default-page-content";
import { isBespokeTemplateSlug } from "./src/lib/templates/bespoke-template-slugs";

interface SeedingResult {
  siteSlug: string;
  siteName: string;
  templateSlug: string | null;
  pagesSeeded: {
    pageId: string;
    pageSlug: string;
    pageTitle: string;
    blocksBefore: number;
    blocksAfter: number;
    success: boolean;
    error?: string;
  }[];
  pagesSkipped: {
    pageId: string;
    pageSlug: string;
    pageTitle: string;
    reason: string;
  }[];
}

interface SeedingSummary {
  totalSitesProcessed: number;
  totalPagesProcessed: number;
  pagesSeeded: number;
  pagesSkipped: number;
  pagesFailed: number;
  breakdownByTemplate: Record<string, {
    pagesSeeded: number;
    pagesSkipped: number;
    pagesFailed: number;
  }>;
}

/**
 * Generic seeding function that works for ANY template.
 * Uses the same logic as the live storefront (mergeBespokeTemplateBlocks)
 * to generate fallback content and persists it to the database.
 */
async function seedPageWithFallbackContent(
  pageId: string,
  templateSlug: string | null,
  pageSlug: string,
  pageTitle: string,
  pageType: string
): Promise<{ success: boolean; blocksCount: number; error?: string }> {
  try {
    // If no template, we can't generate fallback content
    if (!templateSlug) {
      return { success: false, blocksCount: 0, error: 'No template assigned' };
    }

    // Generate blocks using the same logic as the storefront
    const generatedBlocks = mergeBespokeTemplateBlocks(
      templateSlug,
      pageSlug,
      null, // content is null since we're seeding from scratch
      {
        pageSlug,
        pageTitle,
        pageType,
        templateSlug
      }
    );

    if (!generatedBlocks || generatedBlocks.length === 0) {
      return { success: false, blocksCount: 0, error: 'No blocks generated by template system' };
    }

    // Write the generated blocks to the database
    await prisma.page.update({
      where: { id: pageId },
      data: {
        content: {
          blocks: generatedBlocks
        }
      }
    });

    return { success: true, blocksCount: generatedBlocks.length };
  } catch (error) {
    return { success: false, blocksCount: 0, error: error instanceof Error ? error.message : 'Unknown error' };
  }
}

async function seedAllEmptyPages() {
  console.log('=== SEEDING ALL EMPTY PAGES WITH REAL CONTENT ===\n');
  console.log('This script will seed EVERY page with empty blocks across ALL templates...\n');

  const results: SeedingResult[] = [];
  const summary: SeedingSummary = {
    totalSitesProcessed: 0,
    totalPagesProcessed: 0,
    pagesSeeded: 0,
    pagesSkipped: 0,
    pagesFailed: 0,
    breakdownByTemplate: {}
  };

  try {
    // Get ALL sites with their templates and pages
    const sites = await prisma.site.findMany({
      include: {
        templates: {
          where: { isActive: true },
          include: { template: true }
        },
        pages: {
          orderBy: { position: 'asc' }
        }
      }
    });

    for (const site of sites) {
      const activeTemplate = site.templates[0];
      const templateSlug = activeTemplate?.template?.slug || null;

      const siteResult: SeedingResult = {
        siteSlug: site.slug,
        siteName: site.name,
        templateSlug,
        pagesSeeded: [],
        pagesSkipped: []
      };

      // Initialize template breakdown if not exists
      if (templateSlug && !summary.breakdownByTemplate[templateSlug]) {
        summary.breakdownByTemplate[templateSlug] = {
          pagesSeeded: 0,
          pagesSkipped: 0,
          pagesFailed: 0
        };
      }

      for (const page of site.pages) {
        const content = page.content as any;
        const blocks = Array.isArray(content?.blocks) ? content.blocks : [];
        const blocksCount = blocks.length;
        const hasBlocks = blocksCount > 0;

        summary.totalPagesProcessed++;

        // Skip pages that already have real blocks
        if (hasBlocks) {
          siteResult.pagesSkipped.push({
            pageId: page.id,
            pageSlug: page.slug,
            pageTitle: page.title,
            reason: 'Already has real blocks'
          });
          summary.pagesSkipped++;
          if (templateSlug) {
            summary.breakdownByTemplate[templateSlug].pagesSkipped++;
          }
          continue;
        }

        // Try to seed the page with fallback content
        console.log(`Seeding: ${site.name} > ${page.title} (${page.slug}) [${templateSlug || 'no-template'}]`);
        
        const seedResult = await seedPageWithFallbackContent(
          page.id,
          templateSlug,
          page.slug,
          page.title,
          page.type
        );

        if (seedResult.success) {
          siteResult.pagesSeeded.push({
            pageId: page.id,
            pageSlug: page.slug,
            pageTitle: page.title,
            blocksBefore: 0,
            blocksAfter: seedResult.blocksCount,
            success: true
          });
          summary.pagesSeeded++;
          if (templateSlug) {
            summary.breakdownByTemplate[templateSlug].pagesSeeded++;
          }
          console.log(`  ✓ Seeded with ${seedResult.blocksCount} blocks`);
        } else {
          siteResult.pagesSeeded.push({
            pageId: page.id,
            pageSlug: page.slug,
            pageTitle: page.title,
            blocksBefore: 0,
            blocksAfter: 0,
            success: false,
            error: seedResult.error
          });
          summary.pagesFailed++;
          if (templateSlug) {
            summary.breakdownByTemplate[templateSlug].pagesFailed++;
          }
          console.log(`  ✗ Failed: ${seedResult.error}`);
        }
      }

      results.push(siteResult);
      summary.totalSitesProcessed++;
    }

    // Print detailed results
    console.log('\n\n=== DETAILED SEEDING RESULTS BY SITE ===\n');

    for (const result of results) {
      console.log(`\n--- Site: ${result.siteName} (${result.siteSlug}) ---`);
      console.log(`Template: ${result.templateSlug || 'none'}`);
      console.log(`Pages Seeded: ${result.pagesSeeded.filter(p => p.success).length}`);
      console.log(`Pages Skipped: ${result.pagesSkipped.length}`);
      console.log(`Pages Failed: ${result.pagesSeeded.filter(p => !p.success).length}`);

      if (result.pagesSeeded.some(p => p.success)) {
        console.log('\n  Successfully seeded:');
        for (const page of result.pagesSeeded) {
          if (page.success) {
            console.log(`    - ${page.pageTitle} (${page.pageSlug}): ${page.blocksBefore} → ${page.blocksAfter} blocks`);
          }
        }
      }

      if (result.pagesSeeded.some(p => !p.success)) {
        console.log('\n  Failed to seed:');
        for (const page of result.pagesSeeded) {
          if (!page.success) {
            console.log(`    - ${page.pageTitle} (${page.pageSlug}): ${page.error}`);
          }
        }
      }

      if (result.pagesSkipped.length > 0) {
        console.log('\n  Skipped (already has blocks):');
        for (const page of result.pagesSkipped) {
          console.log(`    - ${page.pageTitle} (${page.pageSlug}): ${page.reason}`);
        }
      }
    }

    // Print summary statistics
    console.log('\n\n=== SEEDING SUMMARY ===\n');
    console.log(`Total Sites Processed: ${summary.totalSitesProcessed}`);
    console.log(`Total Pages Processed: ${summary.totalPagesProcessed}`);
    console.log(`Pages Seeded: ${summary.pagesSeeded}`);
    console.log(`Pages Skipped: ${summary.pagesSkipped}`);
    console.log(`Pages Failed: ${summary.pagesFailed}`);

    console.log('\n=== BREAKDOWN BY TEMPLATE ===\n');
    
    const sortedTemplates = Object.entries(summary.breakdownByTemplate).sort((a, b) => b[1].pagesSeeded - a[1].pagesSeeded);

    for (const [templateSlug, stats] of sortedTemplates) {
      console.log(`\n--- Template: ${templateSlug} ---`);
      console.log(`  Pages Seeded: ${stats.pagesSeeded}`);
      console.log(`  Pages Skipped: ${stats.pagesSkipped}`);
      console.log(`  Pages Failed: ${stats.pagesFailed}`);
    }

    // Export results to JSON
    const seedingOutput = {
      summary,
      results
    };

    require('fs').writeFileSync('./seeding-results.json', JSON.stringify(seedingOutput, null, 2));
    console.log('\n\nFull seeding results exported to: seeding-results.json');

  } catch (err) {
    console.error('Error during seeding:', err);
    throw err;
  } finally {
    await prisma.$disconnect();
  }
}

seedAllEmptyPages();
