async function main() {
  console.log("=== FINAL CHANGES TO /src/app/builder/preview/[siteId]/[pageSlug]/page.tsx ===\n");
  
  console.log("CHANGE 1: Add Link import");
  console.log("```diff");
  console.log("+ import Link from 'next/link';");
  console.log("```");
  console.log();
  
  console.log("CHANGE 2: Add state for product/blog data");
  console.log("```diff");
  console.log("+   const [productData, setProductData] = useState<any>(null);");
  console.log("+   const [blogData, setBlogData] = useState<any>(null);");
  console.log("```");
  console.log();
  
  console.log("CHANGE 3: Add useEffect to fetch product/blog data for cosmetics shop/blog pages");
  console.log("```diff");
  console.log("+   // Fetch product/blog data for cosmetics shop/blog pages");
  console.log("+   useEffect(() => {");
  console.log("+     if (!storeData) return;");
  console.log("+     ");
  console.log("+     const { store, templateSlug } = storeData;");
  console.log("+     const storeSlug = store.slug || store.subdomain;");
  console.log("+     ");
  console.log("+     if (templateSlug === 'cosmetics' && pageSlug === 'shop') {");
  console.log("+       fetch(`/api/storefront/${storeSlug}`)");
  console.log("+         .then(res => res.json())");
  console.log("+         .then(json => {");
  console.log("+           if (json.success) setProductData(json.data);");
  console.log("+         })");
  console.log("+         .catch(err => console.error('Failed to fetch product data:', err));");
  console.log("+     }");
  console.log("+     ");
  console.log("+     if (templateSlug === 'cosmetics' && pageSlug === 'blog') {");
  console.log("+       fetch(`/api/storefront/${storeSlug}/blog`)");
  console.log("+         .then(res => res.json())");
  console.log("+         .then(json => {");
  console.log("+           if (json.success) setBlogData(json.data);");
  console.log("+         })");
  console.log("+         .catch(err => console.error('Failed to fetch blog data:', err));");
  console.log("+     }");
  console.log("+   }, [storeData, pageSlug]);");
  console.log("```");
  console.log();
  
  console.log("CHANGE 4: Add renderProductGrid function");
  console.log("```diff");
  console.log("+   // Render product grid for cosmetics shop pages");
  console.log("+   const renderProductGrid = () => {");
  console.log("+     if (templateSlug !== 'cosmetics' || pageSlug !== 'shop' || !productData) return null;");
  console.log("+     const products = productData.products || [];");
  console.log("+     const currency = store.currency || 'NGN';");
  console.log("+     ");
  console.log("+     return (");
  console.log("+       <div className=\"max-w-[1222px] mx-auto px-4 pb-16\">");
  console.log("+         <div className=\"grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4\">");
  console.log("+           {products.map((p: any) => {");
  console.log("+             const hasImage = p.images?.length > 0 && p.images[0].url;");
  console.log("+             return (");
  console.log("+               <div key={p.id} className=\"group\">");
  console.log("+                 <Link href={`/store/${storeSlug}/product/${p.slug}`} className=\"block\">");
  console.log("+                   <div className=\"relative aspect-[3/4] rounded-2xl overflow-hidden mb-3 bg-white\">");
  console.log("+                     {hasImage ? (");
  console.log("+                       <img src={p.images[0].url} alt={p.name} className=\"w-full h-full object-cover transition-transform duration-500 group-hover:scale-110\" />");
  console.log("+                     ) : (");
  console.log("+                       <div className=\"w-full h-full bg-gradient-to-br from-pink-400 to-rose-500 flex items-center justify-center\">");
  console.log("+                         <span className=\"text-white/40 text-4xl font-bold\">{p.name.charAt(0)}</span>");
  console.log("+                       </div>");
  console.log("+                     )}");
  console.log("+                   </div>");
  console.log("+                 </Link>");
  console.log("+                 <Link href={`/store/${storeSlug}/product/${p.slug}`}>");
  console.log("+                   <h3 className=\"text-sm font-semibold text-[#242424] group-hover:text-red-600 transition-colors\">{p.name}</h3>");
  console.log("+                 </Link>");
  console.log("+                 {p.category && <p className=\"text-[10px] text-[#767676] mt-0.5\">{p.category.name}</p>}");
  console.log("+                 <div className=\"flex items-center gap-2 mt-1.5\">");
  console.log("+                   <span className=\"text-base font-bold text-[#242424]\">₦{Number(p.price).toLocaleString()}</span>");
  console.log("+                   {p.compareAtPrice && <span className=\"text-xs text-[#767676] line-through\">₦{Number(p.compareAtPrice).toLocaleString()}</span>}");
  console.log("+                 </div>");
  console.log("+               </div>");
  console.log("+             );");
  console.log("+           })}");
  console.log("+         </div>");
  console.log("+       </div>");
  console.log("+     );");
  console.log("+   };");
  console.log("```");
  console.log();
  
  console.log("CHANGE 5: Add renderBlogList function");
  console.log("```diff");
  console.log("+   // Render blog list for cosmetics blog pages");
  console.log("+   const renderBlogList = () => {");
  console.log("+     if (templateSlug !== 'cosmetics' || pageSlug !== 'blog' || !blogData) return null;");
  console.log("+     const blogs = blogData.blogs || [];");
  console.log("+     ");
  console.log("+     return (");
  console.log("+       <div className=\"max-w-[1222px] mx-auto px-4 pb-16\">");
  console.log("+         <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\">");
  console.log("+           {blogs.map((b: any) => (");
  console.log("+             <Link key={b.id} href={`/store/${storeSlug}/blog/${b.slug}`} className=\"block group\">");
  console.log("+               <div className=\"rounded-2xl overflow-hidden bg-white shadow-sm transition-transform hover:-translate-y-1\">");
  console.log("+                 {b.coverImage ? (");
  console.log("+                   <img src={b.coverImage} alt={b.title} className=\"w-full aspect-[16/10] object-cover\" />");
  console.log("+                 ) : (");
  console.log("+                   <div className=\"w-full aspect-[16/10] bg-gradient-to-br from-purple-400 to-indigo-500 flex items-center justify-center\">");
  console.log("+                     <span className=\"text-white/40 text-4xl font-bold\">{b.title.charAt(0)}</span>");
  console.log("+                   </div>");
  console.log("+                 )}");
  console.log("+                 <div className=\"p-6\">");
  console.log("+                   <h2 className=\"font-bold text-lg text-[#242424] group-hover:text-red-600 transition-colors\">{b.title}</h2>");
  console.log("+                   {b.excerpt && <p className=\"text-sm text-[#767676] mt-2\">{b.excerpt}</p>}");
  console.log("+                   <span className=\"mt-4 inline-flex text-sm font-semibold text-[#242424]\">");
  console.log("+                     Continue reading →");
  console.log("+                   </span>");
  console.log("+                 </div>");
  console.log("+               </div>");
  console.log("+             </Link>");
  console.log("+           ))}");
  console.log("+         </div>");
  console.log("+       </div>");
  console.log("+     );");
  console.log("+   };");
  console.log("```");
  console.log();
  
  console.log("CHANGE 6: Add renders after RenderBlocks");
  console.log("```diff");
  console.log("      <RenderBlocks");
  console.log("        blocks={contentBlocks}");
  console.log("        storeSlug={storeSlug}");
  console.log("        products={products}");
  console.log("        isEditorMode={true}");
  console.log("        wrapBlock={wrapBlockForEditor}");
  console.log("      />");
  console.log("+     {renderProductGrid()}");
  console.log("+     {renderBlogList()}");
  console.log("      {renderFooter()}");
  console.log("```");
  console.log();
  
  console.log("SUMMARY:");
  console.log("- Zero changes to any live-serving file");
  console.log("- Only editor preview modified");
  console.log("- Adds real product/blog data rendering for cosmetics shop/blog pages");
  console.log("- Ensures visual parity between editor and live");
}

main().catch(console.error);
