import type { TemplateBlock } from "@/components/storefront/TemplateBlockRenderer";

export const PROKIP_BOOKING_PRESET: TemplateBlock[] = [
  {
    id: "pb-hero",
    type: "prokipBookingHero",
    props: {
      badge: "Africa's #1 Business software",
      titleLine1: "Trust Is Good.",
      titleHighlight: "Clear Records",
      titleLine3: "Are Better.",
      subtitle: "See how Prokip helps African businesses track sales, stock, staff activities, expenses, and profit from one place — so you can reduce losses, improve control, and grow with confidence.",
      ctaText: "Book your Demo",
      videoId: "npOn8HIb0Yo",
      videoTitle: "How Prokip helped us track sales, stock, and prevent employees theft",
    },
  },
  {
    id: "pb-problem",
    type: "prokipBookingProblemSection",
    props: {
      title: "The Problem Is Not Always Low Sales.",
      titleHighlight: "It Is Poor Visibility.",
      intro: "Many business owners cannot leave their business for long because they are not fully sure what will happen when they are not there. Staff may be working. Sales may be happening. Customers may be buying",
      quotes: [
        "\"Can I trust what my staff are telling me?\"",
        "\"Is my stock complete?\"",
        "\"Are we making profit or just making sales?\"",
        "\"Where is the money going?\"",
      ],
      problems: [
        { icon: "fileQuestion", title: "Stock records do not match reality" },
        { icon: "trendingDown", title: "Cash does not always match sales" },
        { icon: "alertCircle", title: "Expenses increase without clear explanation" },
        { icon: "users", title: "Customers owe money, but records are scattered" },
        { icon: "eyeOff", title: "Reports come late — or not at all" },
        { icon: "helpCircle", title: "When something goes wrong, everyone has an explanation" },
      ],
      outro: "Without clear records, it becomes difficult to know who is responsible, where money is going, and whether the business is truly growing. That uncertainty is stressful. It can also be expensive.",
      ctaText: "Book your free demo",
    },
  },
  {
    id: "pb-solution",
    type: "prokipBookingSolution",
    props: {
      title: "Prokip Helps You See",
      titleHighlight: "What Is Really Happening",
      description: "Prokip is an all-in-one business management system that helps you bring sales, inventory, expenses, accounting, staff activities, customers, suppliers, and reports into one connected system.",
      featuresLabel: "With Prokip, you can instantly see:",
      features: [
        "What was sold", "Who sold it", "What is in stock", "Who moved stock",
        "Who gave discounts", "Who handled returns", "Who owes you money",
        "Which expenses are reducing your profit",
        "Which products, services, or branches are performing best",
        "Whether your business is truly profitable",
      ],
      callout: "When you can see clearly, you can manage better — and grow with less stress.",
      dashboardUrl: "app.prokip.africa/dashboard",
      dashboardStats: { totalSales: "₦245,000", itemsSold: "124" },
    },
  },
  {
    id: "pb-demo-details",
    type: "prokipBookingDemoDetails",
    props: {
      title: "What You Will See During Your Free Demo",
      description: "Your demo is focused on your business, your challenges, and your growth goals. Whether you run a shop, supermarket, pharmacy, restaurant, wholesale business, distribution company, manufacturing business, service business, school, hotel, or multi-branch operation, the demo will be tailored to your business.",
      listHeading: "We will show you how Prokip can help you:",
      benefits: [
        "Reduce employee theft, mistakes, and unauthorized activities",
        "Track every sale, payment, discount, return, and stock movement",
        "Know what is happening even when you are not physically there",
        "Understand whether your business is truly making profit",
        "Monitor expenses and identify where money is being wasted",
        "Manage one location or multiple branches from one place",
        "Keep cleaner records for accounting, reporting, and tax compliance",
        "Build a stronger system that allows your business to grow without depending on you 24/7",
      ],
    },
  },
  {
    id: "pb-testimonials",
    type: "prokipBookingTestimonials",
    props: {
      badge: "Success Stories",
      title: "Hear From Business Owners",
      subtitle: "See how real businesses across Africa use Prokip to take control of their operations and grow confidently.",
      testimonials: [
        { id: "WXfLnZ-iyYA", title: "Business Owner Testimonial 1" },
        { id: "dDeEqanvkRc", title: "Business Owner Testimonial 2" },
      ],
      ctaText: "Book a demo",
    },
  },
  {
    id: "pb-process",
    type: "prokipBookingProcess",
    props: {
      title: "How Your Free Demo Will Go",
      subtitle: "Your Prokip demo is a personalized session focused on your business, not a general software presentation.",
      steps: [
        { num: "1", title: "We Understand Your Business", desc: "We'll ask a few questions about how your business works, your daily operations, your staff, your stock, your sales process, and the challenges you are facing." },
        { num: "2", title: "We Focus on Your Main Problems", desc: "Whether it is missing stock, employee theft, unclear profit, manual records, expenses, customer debts, or managing multiple branches, we'll focus on what matters most to your business." },
        { num: "3", title: "We Show You How Prokip Can Help", desc: "We'll demonstrate how Prokip can help you track sales, monitor stock, know who did what, manage expenses, understand profit, and run your business with better control." },
        { num: "4", title: "We Answer Your Questions", desc: "You can ask about setup, pricing, training, migration, accounting, staff access, branches, and how Prokip fits into your business." },
        { num: "5", title: "You Leave With a Clear Next Step", desc: "By the end, you'll understand how Prokip can help you reduce losses, improve accountability, cut stress, and grow your business with more confidence." },
      ],
    },
  },
  {
    id: "pb-booking-form",
    type: "prokipBookingForm",
    props: {
      title: "Book Your Free",
      titleHighlight: "Personalized Demo",
      subtitle: "Free today. No obligation. Tailored to your business.",
      trustLine: "Trusted by 30,000+ Users",
      trustSubline: "with 1,500+ Local Support Agents in 80+ Regions.",
      countries: [
        { code: "+234", flag: "🇳🇬", name: "Nigeria" },
        { code: "+233", flag: "🇬🇭", name: "Ghana" },
        { code: "+254", flag: "🇰🇪", name: "Kenya" },
        { code: "+27", flag: "🇿🇦", name: "South Africa" },
        { code: "+250", flag: "🇷🇼", name: "Rwanda" },
        { code: "+44", flag: "🇬🇧", name: "United Kingdom" },
        { code: "+1", flag: "🇺🇸", name: "United States" },
      ],
      timeSlots: ["09:00 AM", "10:00 AM", "11:30 AM", "01:00 PM", "02:30 PM", "04:00 PM"],
      businessTypes: [
        { value: "retail", label: "Retail / Supermarket" },
        { value: "pharmacy", label: "Pharmacy" },
        { value: "restaurant", label: "Restaurant / Hotel" },
        { value: "wholesale", label: "Wholesale / Distribution" },
        { value: "manufacturing", label: "Manufacturing" },
        { value: "service", label: "Service Business" },
        { value: "other", label: "Other" },
      ],
      locationOptions: [
        { value: "1", label: "1 (Single Branch)" },
        { value: "2-5", label: "2 - 5 Branches" },
        { value: "6-10", label: "6 - 10 Branches" },
        { value: "11+", label: "11+ Branches" },
      ],
      whyReasons: [
        "They want to know where their money is going.",
        "They want to reduce staff-related losses.",
        "They want to stop depending on manual records.",
        "They want to manage their business without sitting there all day.",
        "They want to expand without losing control.",
      ],
    },
  },
  {
    id: "pb-footer",
    type: "prokipBookingFooter",
    props: {},
  },
];
