/**
 * Nginx config generator for custom domains.
 * Generates server block configs that proxy to the Next.js app and handle SSL via certbot.
 */

export interface NginxConfig {
  domain: string;
  upstreamPort: number;
  includeWww: boolean;
}

/**
 * Generate an Nginx server block config for a custom domain.
 * Handles both www and non-www variants, SSL (certbot placeholder), and proxying to Next.js.
 */
export function generateNginxServerBlock(config: NginxConfig): string {
  const { domain, upstreamPort, includeWww } = config;
  const wwwDomain = `www.${domain}`;

  const serverNames = includeWww
    ? `${domain} ${wwwDomain}`
    : domain;

  return `# Auto-generated by AfroStore Domain Manager
# Domain: ${domain}
# Generated: ${new Date().toISOString()}

# HTTP → HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name ${serverNames};

    # Let's Encrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${serverNames};

    # SSL certificates (managed by certbot)
    ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Proxy to Next.js
    location / {
        proxy_pass http://localhost:${upstreamPort};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
    }

    # Static assets caching
    location /_next/static/ {
        proxy_pass http://localhost:${upstreamPort};
        proxy_cache_valid 200 365d;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # Favicon and robots
    location = /favicon.ico { proxy_pass http://localhost:${upstreamPort}; access_log off; log_not_found off; }
    location = /robots.txt  { proxy_pass http://localhost:${upstreamPort}; access_log off; log_not_found off; }
}
`;
}

/**
 * Generate a filename for the nginx config (safe for filesystem).
 */
export function getNginxConfigFilename(domain: string): string {
  return `${domain.replace(/[^a-zA-Z0-9.-]/g, "_")}.conf`;
}

/**
 * Generate a temporary HTTP-only config (before SSL is provisioned).
 * Used while awaiting cert issuance.
 */
export function generateNginxHttpOnlyBlock(config: Omit<NginxConfig, "includeWww"> & { includeWww?: boolean }): string {
  const { domain, upstreamPort, includeWww = true } = config;
  const wwwDomain = `www.${domain}`;
  const serverNames = includeWww ? `${domain} ${wwwDomain}` : domain;

  return `# Auto-generated by AfroStore Domain Manager (HTTP-only, pre-SSL)
# Domain: ${domain}
# Generated: ${new Date().toISOString()}

server {
    listen 80;
    listen [::]:80;
    server_name ${serverNames};

    # Let's Encrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://localhost:${upstreamPort};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}
`;
}
