export { INTERNAL_TEMPLATES as templateConfigs } from "@/lib/templates/catalog";

export const templateConfigRegistry = {
  panno: "restaurant-pro",
  bakery: "bakery-delight",
  veppo: "accessory-hub",
  lilnest: "kids-world",
  jollys: "kids-world",
  fabulous: "business-services-pro",
  cluum: "business-services-pro",
  lusion: "fashion-luxe",
  noushoes: "footwear-elite",
  fashionworkdo: "fashion-luxe",
  fabulousInterior: "interior-studio",
  restaurantPro: "restaurant-pro",
  bakeryDelight: "bakery-delight",
  accessoryHub: "accessory-hub",
  kidsWorld: "kids-world",
  businessServicesPro: "business-services-pro",
  interiorStudio: "interior-studio",
  commercePro: "commerce-pro",
  // Landing Page Templates
  artsy: "landing-artsy",
  landingArtsy: "landing-artsy",
  scenic: "landing-scenic",
  frolic: "landing-scenic",
  landingScenic: "landing-scenic",
  designpro: "landing-agency",
  dilabs: "landing-agency",
  landingAgency: "landing-agency",
  corba: "landing-service",
  landingService: "landing-service",
  educavo: "landing-education",
  landingEducation: "landing-education",
  landingProduct: "landing-product",
};
