export { INTERNAL_TEMPLATES as templateConfigs } from "@/lib/templates/catalog";

export const templateConfigRegistry = {
  accessories: "accessories",
  foodGrocery: "food-grocery",
  beauty: "beauty",
  artsHandmade: "arts-handmade",
  fashion: "fashion",
  health: "health",
  electronics: "electronics",
  children: "children",
  interiorDesign: "interior-design",
  beverage: "beverage",
  bakery: "bakery",
  digitalServices: "digital-services",
  landingGadget: "landing-gadget",
  aegis: "aegis",
  najafAI: "najaf-ai",
  aurapod: "aurapod",
  artsPortfolio: "arts-portfolio",
  developerPortfolio: "developer-portfolio",
  toybox: "toybox",
  pixapageSaas: "pixapage-saas",
  travelerStartup: "traveler-startup",
  corporate: "corporate",
  lawyer: "lawyer",
  realEstate: "real-estate",
  restaurant: "restaurant",
  modernRestaurant: "modern-restaurant",
  clarity: "clarity",
  agency: "agency",
  portfolio: "portfolio",
  healthcare: "healthcare",
  clinic: "clinic",
  travel: "travel",
  education: "education",
} as const;
