export { INTERNAL_TEMPLATES as templateConfigs } from "@/lib/templates/catalog";

export const templateConfigRegistry = {
  panno: "restaurant-pro",
  bakery: "bakery-delight",
  veppo: "accessory-hub",
  lilnest: "kids-world",
  jollys: "kids-world",
  fabulous: "clarity",
  cluum: "clarity",
  lusion: "fashion-luxe",
  noushoes: "footwear-elite",
  fashionworkdo: "fashion-luxe",
  fabulousInterior: "interior-studio",
  restaurantPro: "restaurant-pro",
  bakeryDelight: "bakery-delight",
  accessoryHub: "accessory-hub",
  kidsWorld: "kids-world",
  businessServicesPro: "clarity",
  // Business Website Templates
  clarity: "clarity",
  arsha: "arsha",
  lawyerCorporate: "lawyer-corporate",
  corporatePro: "corporate-pro",
  realEstatePro: "real-estate-pro",
  bistro: "bistro",
  nutrio: "nutrio",
  medicare: "medicare",
  travely: "travely",
  rival: "rival",
  workfolio: "workfolio",
  strada: "strada",
  melodyEducation: "melody-education",
  interiorStudio: "interior-studio",
  commercePro: "commerce-pro",
  // Jewellery Templates
  jewelleryElegance: "jewellery-elegance",
  jewellery: "jewellery-elegance",
  // Landing Page Templates
  artsy: "landing-artsy",
  landingArtsy: "landing-artsy",
  scenic: "landing-scenic",
  frolic: "landing-scenic",
  landingScenic: "landing-scenic",
  designpro: "landing-agency",
  dilabs: "landing-agency",
  landingAgency: "landing-agency",
  corba: "landing-service",
  landingService: "landing-service",
  educavo: "landing-education",
  landingEducation: "landing-education",
  landingProduct: "landing-product",
};
